CREATE TABLE IF NOT EXISTS `bot_trace_event` (
  `id` bigint(20) unsigned NOT NULL auto_increment,
  `ts` int(10) unsigned NOT NULL default '0',
  `trace_id` varchar(64) NOT NULL default '',
  `bot_id` int(10) unsigned DEFAULT NULL,
  `char_id` int(10) unsigned DEFAULT NULL,
  `account_id` int(10) unsigned DEFAULT NULL,
  `map_id` int(10) unsigned NOT NULL default '0',
  `map_name` varchar(32) NOT NULL default '',
  `x` smallint(5) unsigned NOT NULL default '0',
  `y` smallint(5) unsigned NOT NULL default '0',
  `controller_id` varchar(64) NOT NULL default '',
  `controller_kind` varchar(32) NOT NULL default '',
  `owner_token` varchar(64) NOT NULL default '',
  `phase` enum('controller','scheduler','move','interaction','reservation','reconcile') NOT NULL default 'controller',
  `action` enum('controller.assigned','controller.released','scheduler.spawned','scheduler.parked','move.started','move.completed','move.failed','interaction.requested','interaction.completed','interaction.failed','reservation.acquired','reservation.denied','reservation.released','reconcile.started','reconcile.fixed','reconcile.failed') NOT NULL default 'controller.assigned',
  `target_type` varchar(32) NOT NULL default '',
  `target_id` varchar(64) NOT NULL default '',
  `reason_code` enum('none','operator.start','operator.stop','scheduler.select','scheduler.topup','scheduler.steady','scheduler.not_selected','demand.social','demand.guild','demand.merchant','cooldown','cap.actor','cap.map','claim.lost','path.blocked','target.invalid','script.busy','map.changed','restart.recovery','controller.gate','users.gate','no.demanded_slots','park.policy','pool.available','pool.denied','reconcile.scan','reconcile.sync','interaction.shop','interaction.guild','interaction.party') NOT NULL default 'none',
  `inputs` text DEFAULT NULL,
  `signals` text DEFAULT NULL,
  `reservation_refs` text DEFAULT NULL,
  `result` enum('ok','noop','retry','fallback','aborted','denied','timeout','desynced','fatal') NOT NULL default 'ok',
  `duration_ms` int(10) unsigned NOT NULL default '0',
  `fallback` varchar(64) NOT NULL default '',
  `error_code` varchar(64) NOT NULL default '',
  `error_detail` varchar(191) NOT NULL default '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `trace_id` (`trace_id`),
  KEY `ts` (`ts`),
  KEY `bot_id` (`bot_id`),
  KEY `char_id` (`char_id`),
  KEY `account_id` (`account_id`),
  KEY `map_name` (`map_name`),
  KEY `controller_id` (`controller_id`),
  KEY `action` (`action`),
  KEY `result` (`result`)
) ENGINE=InnoDB;
